import type { ArkheData, ItemStatus, SpecificationItem } from "@/lib/types";

const now = "2026-08-14T15:40:00.000Z";

const project = {
  id: "11111111-1111-4111-8111-111111111111",
  ownerId: "demo-user",
  name: "Soho Residence",
  client: "Isabel & James Mercer",
  status: "In progress" as const,
  location: "SoHo, New York",
  updatedAt: now,
  createdAt: "2026-05-18T09:00:00.000Z",
};

const spaces = [
  { id: "space-living", projectId: project.id, name: "Living Room", sortOrder: 0 },
  { id: "space-kitchen", projectId: project.id, name: "Kitchen", sortOrder: 1 },
  { id: "space-bedroom", projectId: project.id, name: "Primary Bedroom", sortOrder: 2 },
  { id: "space-bathroom", projectId: project.id, name: "Bathroom", sortOrder: 3 },
  { id: "space-entry", projectId: project.id, name: "Entry", sortOrder: 4 },
];

type DemoItem = Omit<SpecificationItem, "projectId" | "createdAt" | "updatedAt">;

const rawItems: DemoItem[] = [
  {
    id: "item-travertine",
    spaceId: "space-entry",
    name: "Honed Travertine Floor Tile",
    category: "Stone & Tile",
    supplier: "ABC Stone",
    description: "Cross-cut Italian travertine in a quiet, filled-and-honed finish. 600 × 600 mm modules.",
    quantity: 38,
    unitPrice: 185,
    leadTimeWeeks: 12,
    status: "Approved",
    notes: "Confirm lot range with fabricator before release.",
    imageUrl: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 0,
  },
  {
    id: "item-oak-panel",
    spaceId: "space-living",
    name: "Rift-Cut Oak Wall Panel",
    category: "Joinery",
    supplier: "New York Woodwork",
    description: "Book-matched white oak veneer panels with a low-sheen natural oil finish.",
    quantity: 26,
    unitPrice: 420,
    leadTimeWeeks: 14,
    status: "Reviewing",
    notes: "Full-height sample requested. Grain direction vertical.",
    imageUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 1,
  },
  {
    id: "item-pendant",
    spaceId: "space-kitchen",
    name: "Patinated Brass Pendant",
    category: "Lighting",
    supplier: "Allied Maker",
    description: "Hand-finished spun brass pendant with opal glass diffuser and blackened stem.",
    quantity: 3,
    unitPrice: 1480,
    leadTimeWeeks: 10,
    status: "Approved",
    notes: "2700K, dim-to-warm driver. Verify stem drop after reflected ceiling plan.",
    imageUrl: "https://images.unsplash.com/photo-1540932239986-30128078f3c5?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 2,
  },
  {
    id: "item-chair",
    spaceId: "space-living",
    name: "Linen Lounge Chair",
    category: "Furniture",
    supplier: "The Invisible Collection",
    description: "Low lounge chair with oak frame and Belgian washed-linen upholstery.",
    quantity: 2,
    unitPrice: 3650,
    leadTimeWeeks: 16,
    status: "Draft",
    notes: "COM yardage pending supplier confirmation.",
    imageUrl: "https://images.unsplash.com/photo-1598300056393-4aac492f4344?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 3,
  },
  {
    id: "item-marble",
    spaceId: "space-kitchen",
    name: "Calacatta Viola Countertop",
    category: "Stone & Tile",
    supplier: "Bergen Marble & Granite",
    description: "Book-matched Calacatta Viola slabs with eased edge and integrated backsplash.",
    quantity: 7.5,
    unitPrice: 980,
    leadTimeWeeks: 8,
    status: "Ordered",
    notes: "Slabs tagged at yard. Template after millwork installation.",
    imageUrl: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 4,
  },
  {
    id: "item-rug",
    spaceId: "space-living",
    name: "Hand-Knotted Wool Area Rug",
    category: "Textiles",
    supplier: "Nordic Knots",
    description: "Custom natural wool rug, low pile, warm oatmeal field with hand-serged edge.",
    quantity: 1,
    unitPrice: 8250,
    leadTimeWeeks: 18,
    status: "Reviewing",
    notes: "Final size 3000 × 4000 mm. Strike-off due 22 August.",
    imageUrl: "https://images.unsplash.com/photo-1600166898405-da9535204843?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 5,
  },
  {
    id: "item-sconce",
    spaceId: "space-bathroom",
    name: "Alabaster Cylinder Sconce",
    category: "Lighting",
    supplier: "Apparatus",
    description: "Hand-carved alabaster shade with aged brass mount, damp-location rated.",
    quantity: 4,
    unitPrice: 1195,
    leadTimeWeeks: 20,
    status: "Approved",
    notes: "Natural stone variation accepted by client.",
    imageUrl: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 6,
  },
  {
    id: "item-faucet",
    spaceId: "space-bathroom",
    name: "Wall-Mounted Basin Mixer",
    category: "Plumbing",
    supplier: "Vola",
    description: "Two-hole wall-mounted basin mixer in unlacquered brushed brass.",
    quantity: 2,
    unitPrice: 1675,
    leadTimeWeeks: 9,
    status: "Ordered",
    notes: "Coordinate rough-in depth with stone vanity build-up.",
    imageUrl: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 7,
  },
  {
    id: "item-bed",
    spaceId: "space-bedroom",
    name: "Upholstered Platform Bed",
    category: "Furniture",
    supplier: "De La Espada",
    description: "Solid walnut platform frame with integral tables and bouclé upholstered headboard.",
    quantity: 1,
    unitPrice: 12400,
    leadTimeWeeks: 22,
    status: "Draft",
    notes: "Awaiting revised shop drawing for US king mattress.",
    imageUrl: "https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 8,
  },
  {
    id: "item-drapery",
    spaceId: "space-bedroom",
    name: "Sheer Linen Drapery",
    category: "Textiles",
    supplier: "Rose Uniacke",
    description: "Full-height hand-finished sheer linen with concealed wave track.",
    quantity: 18,
    unitPrice: 310,
    leadTimeWeeks: 11,
    status: "Reviewing",
    notes: "Price per linear yard inclusive of fabrication.",
    imageUrl: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 9,
  },
  {
    id: "item-console",
    spaceId: "space-entry",
    name: "Bronze & Oak Console",
    category: "Furniture",
    supplier: "Roman and Williams Guild",
    description: "Narrow console with cast bronze frame and hand-planed fumed oak top.",
    quantity: 1,
    unitPrice: 7600,
    leadTimeWeeks: 24,
    status: "Approved",
    notes: "Wall cleat required; coordinate with limewash finish.",
    imageUrl: "https://images.unsplash.com/photo-1538688423619-a81d3f23454b?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 10,
  },
  {
    id: "item-stool",
    spaceId: "space-kitchen",
    name: "Leather Counter Stool",
    category: "Furniture",
    supplier: "Børge Mogensen Archive",
    description: "Oak counter stool with hand-stitched saddle leather seat.",
    quantity: 4,
    unitPrice: 1450,
    leadTimeWeeks: 13,
    status: "Draft",
    notes: "Seat height 650 mm; natural vegetable-tanned leather.",
    imageUrl: "https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=1200&q=82",
    sortOrder: 11,
  },
];

export const demoData: ArkheData = {
  project,
  spaces,
  items: rawItems.map((item) => ({ ...item, projectId: project.id, createdAt: now, updatedAt: now })),
  attachments: [],
  shareLinks: [],
};

export const activityFeed = [
  { id: "activity-1", action: "Price updated", subject: "Calacatta Viola Countertop", detail: "$980 / m²", at: "Today, 11:42" },
  { id: "activity-2", action: "Status approved", subject: "Patinated Brass Pendant", detail: "Kitchen", at: "Yesterday, 16:08" },
  { id: "activity-3", action: "Note added", subject: "Hand-Knotted Wool Area Rug", detail: "Strike-off requested", at: "12 Aug, 09:31" },
  { id: "activity-4", action: "Item ordered", subject: "Wall-Mounted Basin Mixer", detail: "2 units", at: "10 Aug, 14:16" },
];

export function statusTone(status: ItemStatus) {
  return status.toLowerCase();
}
